Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,17 +29,17 @@ jobs:
         run: |
           python record.py
 
-      - name: Commit & push recording
-        env:
-          MY_TOKEN: ${{ secrets.MY_TOKEN }}
-        run: |
-          git config --global user.email "madyapadma_trisma@yahoo.com"
-          git config --global user.name "GitHub Actions"
+      # - name: Commit & push recording
+      #   env:
+      #     MY_TOKEN: ${{ secrets.MY_TOKEN }}
+      #   run: |
+      #     git config --global user.email "madyapadma_trisma@yahoo.com"
+      #     git config --global user.name "GitHub Actions"
 
-          git add recordings/
-          git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"
+      #     git add recordings/
+      #     git commit -m "Add raw recording at $(date -u)" || echo "No changes to commit"
 
-          git remote set-url origin https://x-access-token:${MY_TOKEN}@github.com/Sparkplugx1904/VOT-Denpasar.git
-          git config --local --unset-all http.https://github.com/.extraheader || true
+      #     git remote set-url origin https://x-access-token:${MY_TOKEN}@github.com/Sparkplugx1904/VOT-Denpasar.git
+      #     git config --local --unset-all http.https://github.com/.extraheader || true
           
-          git push origin main || echo "[ERROR] Push gagal"
+      #     git push origin main || echo "[ERROR] Push gagal"
